[development]
DB_ENV = "zipdrug-development-db"
S3_ARCHIVE_BUCKET = "zipdrug-data-lake"
S3_ARCHIVE_PREFIX = "etl/test/"

[stage]
DB_ENV = "zipdrug-stage-db"

[production]
DB_ENV = "production-api-db"
